### ISSUE TITLE
entity is incorrectly being triggered for updates while it is disabled

### ISSUE THREAD

**Issue by nenonano** [weltmeyer/ha_snmp_stats#1]
hi there.. using your integration 
I disabled many entities as I'm not interested in monitoring them.. 
anyway, I see many lines like this one in my logs:

WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.snmp_stats_192_168_0_1_netif_br_lan_curbw_out_mbit is incorrectly being triggered for updates while it is disabled. This is a bug in the snmp_stats integration.

**Comment by weltmeyer** [comment]
Hi nenonano, this should be fixed with the latest version :)

**Comment by nenonano** [comment]
ok, after upgrading messages are gone, thank you

**Comment by weltmeyer** [comment]
thanks for reporting back :) closing this.
