### ISSUE TITLE
How can I enable this component?

### ISSUE THREAD

**Issue by hungpr0** [weltmeyer/ha_snmp_stats#3]
Hello,
I added this repo as custom repo. I installed it via HACS but it seems the component is lacking info on how to enable.
Is there setting that needs to be added to configuration.yaml?
I tried to add configuration->intergrations--> + snmp_stats. Message seems to be blank on "Submit"

I'm using
Home Assistant 0.113.3
HACS 1.3.3

Please help.
Thanks

**Comment by hebermc** [comment]
I think its IP, but I get an error: [**EDIT**: it is]

```
  File "/config/custom_components/snmp_stats/config_flow.py", line 36, in async_step_user
    SnmpStatisticsMonitor(ipaddress)
  File "/config/custom_components/snmp_stats/sensor.py", line 119, in __init__
    self.update_stats()#try this to throw error if not working.
  File "/config/custom_components/snmp_stats/sensor.py", line 192, in update_stats
    self.update_netif_stats()
  File "/config/custom_components/snmp_stats/sensor.py", line 221, in update_netif_stats
    its = __class__.get_bulk_auto(self.target_ip, [
  File "/config/custom_components/snmp_stats/sensor.py", line 158, in get_bulk_auto
    count = __class__.get(target, [count_oid], credentials, port, engine, context)[count_oid]
  File "/config/custom_components/snmp_stats/sensor.py", line 133, in get
    return __class__.fetch(handler, 1)[0]
  File "/config/custom_components/snmp_stats/sensor.py", line 185, in fetch
    raise RuntimeError('Got SNMP error: {0}'.format(error_indication))
RuntimeError: Got SNMP error: No SNMP response received before timeout
```

I suppose something needs configuring in SNMP, I just can't figure out what. Using "Paessler SNMP Tester" on the router IP I get error #2003

**EDIT**: Did this: https://kb.opservices.com/knowledge-base/habilitando-snmp-linux-2/ and now it works. Also got lots of stuff in "Paesler SNMP Tester".  Linux users can probably just do snmpwalk

**Comment by weltmeyer** [comment]
> Hello,
> I added this repo as custom repo. I installed it via HACS but it seems the component is lacking info on how to enable.
> Is there setting that needs to be added to configuration.yaml?
> I tried to add configuration->intergrations--> + snmp_stats. Message seems to be blank on "Submit"
> 
> I'm using
> Home Assistant 0.113.3
> HACS 1.3.3
> 
> Please help.
> Thanks

Logs please :)
